name: ligaduck
description: "A new Flutter project."
publish_to: "none"
version: 43.00.00

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.1.1
  http: ^0.13.6
  provider: ^6.1.1
  oktoast: ^3.3.1
  file_selector: ^1.0.4
  smooth_page_indicator: ^1.1.0
  csv: ^6.0.0
  mongo_dart: ^0.10.0
  font_awesome_flutter: ^10.7.0
  glassmorphism: ^3.0.0
  shared_preferences: ^2.2.2
  keyboard_actions: ^4.2.0
  package_info_plus: ^7.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.3.1
  build_runner: any

flutter_icons:
  ios: true
  android: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  macos:
    generate: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Elms Sans
      fonts:
        - asset: assets/font/framd.ttf
    - family: champions
      fonts:
        - asset: assets/font/champions.ttf
    - family: europa
      fonts:
        - asset: assets/font/europa.ttf
    - family: supercup
      fonts:
        - asset: assets/font/supercup.otf
  assets:
    #icone
    - assets/icon/

    #loghi competizione
    - assets/logos/

    #loghi squadre
    - assets/squadre/

    #divise
    - assets/divise/divise_43/

    #miscellaneous
    - assets/miscellaneous/

    #trofei
    - assets/trophies/

    #nazioni
    - assets/nations/
