name: ligaduck
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  http: ^0.13.6
  provider: ^6.1.1
  oktoast: ^3.3.1
  file_picker: ^5.2.5
  smooth_page_indicator: ^1.1.0
  csv: ^6.0.0
  mongo_dart: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.1
  build_runner: any

flutter_icons:
  ios: true
  android: true
  macos:
    generate: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Franklin Gothic
      fonts:
        - asset: assets/font/framd.ttf
  assets:
    #loghi competizione
    - assets/logos/logo_liga_duck.png
    - assets/logos/logo_coppa_dei_paperi.png
    - assets/logos/logo_coppa_di_lega.png
    - assets/logos/logo_supercoppa_dei_paperi.png
    - assets/logos/logo_champions_league.png
    - assets/logos/logo_europa_league.png
    - assets/logos/logo_conference_league.png
    - assets/logos/logo_supercoppa_europea.png
    - assets/logos/logo_coppa_intercontinentale.png
    - assets/logos/logo_mondiale_per_club_fifa.png

    #loghi squadre
    - assets/squadre/atletico_ocaville.png
    - assets/squadre/black_fury.png
    - assets/squadre/canal_city.png
    - assets/squadre/cavaria_city.png
    - assets/squadre/freddonia.png
    - assets/squadre/golden_city.png
    - assets/squadre/luponia.png
    - assets/squadre/milanpaper.png
    - assets/squadre/ors_city.png
    - assets/squadre/palmipedy_city.png
    - assets/squadre/paperi_diavoli.png
    - assets/squadre/paperinter.png
    - assets/squadre/paperonia.png
    - assets/squadre/paperopoli.png
    - assets/squadre/papersamp.png
    - assets/squadre/paperville.png
    - assets/squadre/pipponia.png
    - assets/squadre/spettropoli.png
    - assets/squadre/topolinia.png
    - assets/squadre/torelli.png

    #divise
    - assets/divise/divise_43/atletico_ocaville_1.png
    - assets/divise/divise_43/atletico_ocaville_2.png
    - assets/divise/divise_43/atletico_ocaville_3.png
    - assets/divise/divise_43/black_fury_1.png
    - assets/divise/divise_43/black_fury_2.png
    - assets/divise/divise_43/black_fury_3.png
    - assets/divise/divise_43/canal_city_1.png
    - assets/divise/divise_43/canal_city_2.png
    - assets/divise/divise_43/canal_city_3.png
    - assets/divise/divise_43/cavaria_city_1.png
    - assets/divise/divise_43/cavaria_city_2.png
    - assets/divise/divise_43/cavaria_city_3.png
    - assets/divise/divise_43/freddonia_1.png
    - assets/divise/divise_43/freddonia_2.png
    - assets/divise/divise_43/freddonia_3.png
    - assets/divise/divise_43/golden_city_1.png
    - assets/divise/divise_43/golden_city_2.png
    - assets/divise/divise_43/golden_city_3.png
    - assets/divise/divise_43/luponia_1.png
    - assets/divise/divise_43/luponia_2.png
    - assets/divise/divise_43/luponia_3.png
    - assets/divise/divise_43/milanpaper_1.png
    - assets/divise/divise_43/milanpaper_2.png
    - assets/divise/divise_43/milanpaper_3.png
    - assets/divise/divise_43/ors_city_1.png
    - assets/divise/divise_43/ors_city_2.png
    - assets/divise/divise_43/ors_city_3.png
    - assets/divise/divise_43/palmipedy_city_1.png
    - assets/divise/divise_43/palmipedy_city_2.png
    - assets/divise/divise_43/palmipedy_city_3.png
    - assets/divise/divise_43/paperi_diavoli_1.png
    - assets/divise/divise_43/paperi_diavoli_2.png
    - assets/divise/divise_43/paperi_diavoli_3.png
    - assets/divise/divise_43/paperinter_1.png
    - assets/divise/divise_43/paperinter_2.png
    - assets/divise/divise_43/paperinter_3.png
    - assets/divise/divise_43/paperonia_1.png
    - assets/divise/divise_43/paperonia_2.png
    - assets/divise/divise_43/paperonia_3.png
    - assets/divise/divise_43/paperopoli_1.png
    - assets/divise/divise_43/paperopoli_2.png
    - assets/divise/divise_43/paperopoli_3.png
    - assets/divise/divise_43/papersamp_1.png
    - assets/divise/divise_43/papersamp_2.png
    - assets/divise/divise_43/papersamp_3.png
    - assets/divise/divise_43/paperville_1.png
    - assets/divise/divise_43/paperville_2.png
    - assets/divise/divise_43/paperville_3.png
    - assets/divise/divise_43/pipponia_1.png
    - assets/divise/divise_43/pipponia_2.png
    - assets/divise/divise_43/pipponia_3.png
    - assets/divise/divise_43/spettropoli_1.png
    - assets/divise/divise_43/spettropoli_2.png
    - assets/divise/divise_43/spettropoli_3.png
    - assets/divise/divise_43/topolinia_1.png
    - assets/divise/divise_43/topolinia_2.png
    - assets/divise/divise_43/topolinia_3.png
    - assets/divise/divise_43/torelli_1.png
    - assets/divise/divise_43/torelli_2.png
    - assets/divise/divise_43/torelli_3.png

    #miscellaneous
    - assets/miscellaneous/stadium.png
    - assets/miscellaneous/divisa_1.png

    #trofei
    - assets/trophies/liga_duck.png
    - assets/trophies/coppa_dei_paperi.png
    - assets/trophies/coppa_di_lega.png
    - assets/trophies/supercoppa_dei_paperi.png
    - assets/trophies/serie_b.png
    - assets/trophies/champions_league.png
    - assets/trophies/europa_league.png
    - assets/trophies/conference_league.png
    - assets/trophies/supercoppa_europea.png
    - assets/trophies/coppa_delle_coppe.png
    - assets/trophies/mitropa_cup.png
    - assets/trophies/mondiale_per_club.png
    - assets/trophies/mondiale_per_club_fifa.png
    - assets/trophies/coppa_intercontinentale.png

    #nazioni
    - assets/nations/italy.png
