import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/country.dart';

class CountryService {
  // API REST countries con traduzioni italiane
  static const String apiUrl =
      'https://restcountries.com/v3.1/all?fields=name,translations,cca2,cca3,flags,flag';

  static Future<List<Country>> getAllCountries() async {
    try {
      print('Caricamento nazioni da REST countries API...');
      final response = await http.get(Uri.parse(apiUrl));

      if (response.statusCode == 200) {
        final decoded = json.decode(response.body);
        if (decoded is! List) {
          print(
            'Risposta API non valida: attesa List, ricevuto ${decoded.runtimeType}',
          );
          return _getStaticCountries();
        }
        final data = decoded;
        List<Country> countries = data
            .map((json) => Country.fromJsonWithItalian(json))
            .toList();

        // Ordina per nome italiano
        countries.sort((a, b) => a.commonName.compareTo(b.commonName));

        print('Caricate ${countries.length} nazioni in italiano');
        return countries;
      }
    } catch (e) {
      print('Errore nel caricamento delle nazioni: $e');
    }

    // Se l'API fallisce, usa la lista statica
    return _getStaticCountries();
  }

  // Lista statica di nazioni per fallback immediato
  static List<Country> _getStaticCountries() {
    final List<Map<String, String>> staticCountries = [
      {'name': 'Afghanistan', 'code': 'AF'},
      {'name': 'Albania', 'code': 'AL'},
      {'name': 'Algeria', 'code': 'DZ'},
      {'name': 'Andorra', 'code': 'AD'},
      {'name': 'Angola', 'code': 'AO'},
      {'name': 'Antigua e Barbuda', 'code': 'AG'},
      {'name': 'Arabia Saudita', 'code': 'SA'},
      {'name': 'Argentina', 'code': 'AR'},
      {'name': 'Armenia', 'code': 'AM'},
      {'name': 'Australia', 'code': 'AU'},
      {'name': 'Austria', 'code': 'AT'},
      {'name': 'Azerbaigian', 'code': 'AZ'},
      {'name': 'Bahamas', 'code': 'BS'},
      {'name': 'Bahrein', 'code': 'BH'},
      {'name': 'Bangladesh', 'code': 'BD'},
      {'name': 'Barbados', 'code': 'BB'},
      {'name': 'Belgio', 'code': 'BE'},
      {'name': 'Belize', 'code': 'BZ'},
      {'name': 'Benin', 'code': 'BJ'},
      {'name': 'Bhutan', 'code': 'BT'},
      {'name': 'Bielorussia', 'code': 'BY'},
      {'name': 'Bolivia', 'code': 'BO'},
      {'name': 'Bosnia ed Erzegovina', 'code': 'BA'},
      {'name': 'Botswana', 'code': 'BW'},
      {'name': 'Brasile', 'code': 'BR'},
      {'name': 'Brunei', 'code': 'BN'},
      {'name': 'Bulgaria', 'code': 'BG'},
      {'name': 'Burkina Faso', 'code': 'BF'},
      {'name': 'Burundi', 'code': 'BI'},
      {'name': 'Cambogia', 'code': 'KH'},
      {'name': 'Camerun', 'code': 'CM'},
      {'name': 'Canada', 'code': 'CA'},
      {'name': 'Capo Verde', 'code': 'CV'},
      {'name': 'Ciad', 'code': 'TD'},
      {'name': 'Cile', 'code': 'CL'},
      {'name': 'Cina', 'code': 'CN'},
      {'name': 'Cipro', 'code': 'CY'},
      {'name': 'Colombia', 'code': 'CO'},
      {'name': 'Comore', 'code': 'KM'},
      {'name': 'Congo', 'code': 'CG'},
      {'name': 'Corea del Nord', 'code': 'KP'},
      {'name': 'Corea del Sud', 'code': 'KR'},
      {'name': 'Costa d\'Avorio', 'code': 'CI'},
      {'name': 'Costa Rica', 'code': 'CR'},
      {'name': 'Croazia', 'code': 'HR'},
      {'name': 'Cuba', 'code': 'CU'},
      {'name': 'Danimarca', 'code': 'DK'},
      {'name': 'Ecuador', 'code': 'EC'},
      {'name': 'Egitto', 'code': 'EG'},
      {'name': 'El Salvador', 'code': 'SV'},
      {'name': 'Emirati Arabi Uniti', 'code': 'AE'},
      {'name': 'Eritrea', 'code': 'ER'},
      {'name': 'Estonia', 'code': 'EE'},
      {'name': 'Eswatini', 'code': 'SZ'},
      {'name': 'Etiopia', 'code': 'ET'},
      {'name': 'Figi', 'code': 'FJ'},
      {'name': 'Filippine', 'code': 'PH'},
      {'name': 'Finlandia', 'code': 'FI'},
      {'name': 'Francia', 'code': 'FR'},
      {'name': 'Gabon', 'code': 'GA'},
      {'name': 'Galles', 'code': 'GB-WLS'},
      {'name': 'Gambia', 'code': 'GM'},
      {'name': 'Georgia', 'code': 'GE'},
      {'name': 'Germania', 'code': 'DE'},
      {'name': 'Ghana', 'code': 'GH'},
      {'name': 'Giamaica', 'code': 'JM'},
      {'name': 'Giappone', 'code': 'JP'},
      {'name': 'Gibuti', 'code': 'DJ'},
      {'name': 'Giordania', 'code': 'JO'},
      {'name': 'Grecia', 'code': 'GR'},
      {'name': 'Guatemala', 'code': 'GT'},
      {'name': 'Guinea', 'code': 'GN'},
      {'name': 'Guinea Bissau', 'code': 'GW'},
      {'name': 'Guinea Equatoriale', 'code': 'GQ'},
      {'name': 'Guyana', 'code': 'GY'},
      {'name': 'Haiti', 'code': 'HT'},
      {'name': 'Honduras', 'code': 'HN'},
      {'name': 'India', 'code': 'IN'},
      {'name': 'Indonesia', 'code': 'ID'},
      {'name': 'Inghilterra', 'code': 'GB-ENG'},
      {'name': 'Iran', 'code': 'IR'},
      {'name': 'Iraq', 'code': 'IQ'},
      {'name': 'Irlanda', 'code': 'IE'},
      {'name': 'Irlanda del Nord', 'code': 'GB-NIR'},
      {'name': 'Islanda', 'code': 'IS'},
      {'name': 'Isole Marshall', 'code': 'MH'},
      {'name': 'Isole Salomone', 'code': 'SB'},
      {'name': 'Israele', 'code': 'IL'},
      {'name': 'Italia', 'code': 'IT'},
      {'name': 'Kazakhstan', 'code': 'KZ'},
      {'name': 'Kenya', 'code': 'KE'},
      {'name': 'Kirghizistan', 'code': 'KG'},
      {'name': 'Kiribati', 'code': 'KI'},
      {'name': 'Kosovo', 'code': 'XK'},
      {'name': 'Kuwait', 'code': 'KW'},
      {'name': 'Laos', 'code': 'LA'},
      {'name': 'Lesotho', 'code': 'LS'},
      {'name': 'Lettonia', 'code': 'LV'},
      {'name': 'Libano', 'code': 'LB'},
      {'name': 'Liberia', 'code': 'LR'},
      {'name': 'Libia', 'code': 'LY'},
      {'name': 'Liechtenstein', 'code': 'LI'},
      {'name': 'Lituania', 'code': 'LT'},
      {'name': 'Lussemburgo', 'code': 'LU'},
      {'name': 'Madagascar', 'code': 'MG'},
      {'name': 'Malawi', 'code': 'MW'},
      {'name': 'Maldive', 'code': 'MV'},
      {'name': 'Malesia', 'code': 'MY'},
      {'name': 'Mali', 'code': 'ML'},
      {'name': 'Malta', 'code': 'MT'},
      {'name': 'Marocco', 'code': 'MA'},
      {'name': 'Mauritania', 'code': 'MR'},
      {'name': 'Mauritius', 'code': 'MU'},
      {'name': 'Messico', 'code': 'MX'},
      {'name': 'Moldavia', 'code': 'MD'},
      {'name': 'Monaco', 'code': 'MC'},
      {'name': 'Mongolia', 'code': 'MN'},
      {'name': 'Montenegro', 'code': 'ME'},
      {'name': 'Mozambico', 'code': 'MZ'},
      {'name': 'Myanmar', 'code': 'MM'},
      {'name': 'Namibia', 'code': 'NA'},
      {'name': 'Nepal', 'code': 'NP'},
      {'name': 'Nicaragua', 'code': 'NI'},
      {'name': 'Niger', 'code': 'NE'},
      {'name': 'Nigeria', 'code': 'NG'},
      {'name': 'Norvegia', 'code': 'NO'},
      {'name': 'Nuova Zelanda', 'code': 'NZ'},
      {'name': 'Olanda', 'code': 'NL'},
      {'name': 'Oman', 'code': 'OM'},
      {'name': 'Pakistan', 'code': 'PK'},
      {'name': 'Palau', 'code': 'PW'},
      {'name': 'Panama', 'code': 'PA'},
      {'name': 'Papua Nuova Guinea', 'code': 'PG'},
      {'name': 'Paraguay', 'code': 'PY'},
      {'name': 'Perù', 'code': 'PE'},
      {'name': 'Polonia', 'code': 'PL'},
      {'name': 'Portogallo', 'code': 'PT'},
      {'name': 'Qatar', 'code': 'QA'},
      {'name': 'Repubblica Ceca', 'code': 'CZ'},
      {'name': 'Repubblica Centrafricana', 'code': 'CF'},
      {'name': 'Repubblica del Congo', 'code': 'CD'},
      {'name': 'Repubblica Dominicana', 'code': 'DO'},
      {'name': 'Romania', 'code': 'RO'},
      {'name': 'Ruanda', 'code': 'RW'},
      {'name': 'Russia', 'code': 'RU'},
      {'name': 'Saint Kitts e Nevis', 'code': 'KN'},
      {'name': 'Saint Lucia', 'code': 'LC'},
      {'name': 'Saint Vincent e Grenadine', 'code': 'VC'},
      {'name': 'Samoa', 'code': 'WS'},
      {'name': 'San Marino', 'code': 'SM'},
      {'name': 'São Tomé e Príncipe', 'code': 'ST'},
      {'name': 'Senegal', 'code': 'SN'},
      {'name': 'Serbia', 'code': 'RS'},
      {'name': 'Seychelles', 'code': 'SC'},
      {'name': 'Sierra Leone', 'code': 'SL'},
      {'name': 'Singapore', 'code': 'SG'},
      {'name': 'Siria', 'code': 'SY'},
      {'name': 'Slovacchia', 'code': 'SK'},
      {'name': 'Slovenia', 'code': 'SI'},
      {'name': 'Somalia', 'code': 'SO'},
      {'name': 'Scozia', 'code': 'GB-SCT'},
      {'name': 'Spagna', 'code': 'ES'},
      {'name': 'Sri Lanka', 'code': 'LK'},
      {'name': 'Stati Uniti', 'code': 'US'},
      {'name': 'Sudafrica', 'code': 'ZA'},
      {'name': 'Sudan', 'code': 'SD'},
      {'name': 'Sudan del Sud', 'code': 'SS'},
      {'name': 'Suriname', 'code': 'SR'},
      {'name': 'Svezia', 'code': 'SE'},
      {'name': 'Svizzera', 'code': 'CH'},
      {'name': 'Tagikistan', 'code': 'TJ'},
      {'name': 'Tanzania', 'code': 'TZ'},
      {'name': 'Thailandia', 'code': 'TH'},
      {'name': 'Timor Est', 'code': 'TL'},
      {'name': 'Togo', 'code': 'TG'},
      {'name': 'Trinidad e Tobago', 'code': 'TT'},
      {'name': 'Tunisia', 'code': 'TN'},
      {'name': 'Turchia', 'code': 'TR'},
      {'name': 'Turkmenistan', 'code': 'TM'},
      {'name': 'Uganda', 'code': 'UG'},
      {'name': 'Ucraina', 'code': 'UA'},
      {'name': 'Ungheria', 'code': 'HU'},
      {'name': 'Uruguay', 'code': 'UY'},
      {'name': 'Uzbekistan', 'code': 'UZ'},
      {'name': 'Vanuatu', 'code': 'VU'},
      {'name': 'Venezuela', 'code': 'VE'},
      {'name': 'Vietnam', 'code': 'VN'},
      {'name': 'Yemen', 'code': 'YE'},
      {'name': 'Zambia', 'code': 'ZM'},
      {'name': 'Zimbabwe', 'code': 'ZW'},
    ];

    return staticCountries.map((countryData) {
      final code = countryData['code']!;
      final region = _europeanCodes.contains(code) ? 'Europe' : 'Other';
      return Country(
        commonName: countryData['name']!,
        officialName: countryData['name']!,
        region: region,
        subregion: '',
        population: 0,
        area: 0,
        currencies: [],
        languages: [],
        flagUrl: '',
        flagEmoji: '',
        cca2: code,
        cca3: code,
      );
    }).toList();
  }

  static const Set<String> _europeanCodes = {
    'AL',
    'AD',
    'AM',
    'AT',
    'AZ',
    'BY',
    'BE',
    'BA',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'GE',
    'DE',
    'GR',
    'HU',
    'IS',
    'IE',
    'IL',
    'IT',
    'XK',
    'LV',
    'LI',
    'LT',
    'LU',
    'MT',
    'MD',
    'MC',
    'ME',
    'NL',
    'MK',
    'NO',
    'PL',
    'PT',
    'RO',
    'RU',
    'SM',
    'RS',
    'SK',
    'SI',
    'ES',
    'SE',
    'CH',
    'TR',
    'UA',
    'GB',
    'GB-ENG',
    'GB-SCT',
    'GB-WLS',
    'GB-NIR',
  };
}
